export const content = {
  nav: {
    logo: "PENALTYIQ",
    links: [
      { label: "Home", href: "/" },
      { label: "Explore", href: "/demo" },
      { label: "History", href: "/history", authRequired: true },
      { label: "Favorites", href: "#", disabled: true },
      { label: "Profile", href: "#", disabled: true },
    ],
  },
  hero: {
    title: "Perfect Your Penalty",
    subtitle: "AI-powered biomechanical analysis of your penalty kicks. Track, score, and improve with actionable coaching.",
    cta: "GET STARTED",
    demo: "WATCH DEMO",
  },
  features: [
    { title: "Upload", description: "Upload your penalty kick video in MP4 or WebM format.", icon: "upload" },
    { title: "Track", description: "MediaPipe Pose tracks 33 body landmarks across every frame.", icon: "track" },
    { title: "Score", description: "Deterministic scoring across 5 biomechanical dimensions.", icon: "score" },
    { title: "Coach", description: "Get AI-generated coaching tips from our BitNet model.", icon: "coach" },
  ],
  capture: {
    uploadLabel: "Upload Video",
    uploadHint: "MP4 or WebM, max 100MB",
    contactFrameButton: "This is the contact frame",
    kickingFootLabel: "Kicking Foot",
    rightFoot: "Right",
    leftFoot: "Left",
    captureSuccess: "Captured!",
    processing: "Processing...",
  },
  dashboard: {
    techniqueScore: "Technique Score",
    trackingConfidence: "Tracking Confidence",
    sessionsAnalyzed: "Sessions Analyzed",
    subScoreDelta: "vs. Last Session",
    diagnostics: "Diagnostics",
    upload: "Upload",
    history: "History",
    compare: "Compare",
    settings: "Settings",
    aiCoachTitle: "PENALTY_IQ // AI COACH",
    statusReady: "Local model · Ready",
    statusOffline: "Offline",
    statusLoading: "Loading",
    chips: [
      { label: "Analyze Latest", action: "analyze" },
      { label: "Compare Sessions", action: "compare" },
      { label: "Export Report", action: "export" },
      { label: "Drill Suggestions", action: "drills" },
      { label: "Session Summary", action: "summary" },
    ],
    askCoach: "Ask the Coach (online)",
    inputPlaceholder: "Ask a question about your technique...",
  },
  history: {
    title: "Session History",
    emptyTitle: "No sessions yet",
    emptyDescription: "Upload your first video to get started",
    emptyCta: "Upload Video",
    statusPending: "Pending",
    statusProcessing: "Processing",
    statusComplete: "Complete",
    statusError: "Error",
    viewLink: "View",
  },
  demo: {
    title: "Watch Demo",
    description: "See how PenaltyIQ analyzes a penalty kick in real-time.",
  },
  errors: {
    authRequired: "Please sign in to access this page.",
    uploadFailed: "Failed to upload video. Please try again.",
    captureFailed: "Failed to capture contact frame. Please try again.",
  },
};
